# Generated by Django 3.1.5 on 2021-03-16 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_auto_20210316_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved_comment',
        ),
    ]
