# Generated by Django 3.1.5 on 2021-03-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_remove_comment_approved_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='head_image',
            field=models.ImageField(null=True, upload_to='blogimage/'),
        ),
    ]
